using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HitBtcApi.Model
{
    public class Trade
    {
        /// <summary>
        /// Trade ID on the exchange
        /// </summary>
        public int tradeId { get; set; }

        /// <summary>
        /// Trade price
        /// </summary>
        public double execPrice { get; set; }

        /// <summary>
        /// Timestamp, in milliseconds
        /// </summary>
        public object timestamp { get; set; }

        /// <summary>
        /// Order ID on the exchange
        /// </summary>
        public string originalOrderId { get; set; }

        /// <summary>
        /// Fee for the trade, negative value means rebate
        /// </summary>
        public double fee { get; set; }

        /// <summary>
        /// Unique order ID generated by client. From 8 to 32 characters
        /// </summary>
        public string clientOrderId { get; set; }

        /// <summary>
        /// Currency symbol
        /// </summary>
        public string symbol { get; set; }

        /// <summary>
        /// Side of a trade
        /// </summary>
        public string side { get; set; }

        /// <summary>
        /// Trade size, in lots
        /// </summary>
        public int execQuantity { get; set; }
    }

    public class SpecifiedTrade
    {
        public object date { get; set; }
        public string price { get; set; }
        public string amount { get; set; }
        public int tid { get; set; }
        public string side { get; set; }
    }

    public class Trades
    {
        public List<Trade> trades { get; set; }
    }

    public class SpecifiedTrades
    {
        public List<SpecifiedTrade> trades { get; set; }
    }
}
